# Generated by Django 5.0.4 on 2026-09-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "business_id",
                    models.CharField(
                        error_messages={
                            "unique": "A Company with the same business ID already exists"
                        },
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=100)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="companies/logos"
                    ),
                ),
                ("address", models.CharField(max_length=40)),
                ("city", models.CharField(max_length=40)),
                ("state", models.CharField(max_length=40)),
                ("country", models.CharField(max_length=40)),
            ],
            options={
                "ordering": ["-name", "-business_id"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
    ]
