# Generated by Django 5.0.4 on 2024-04-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "personal_id",
                    models.IntegerField(
                        error_messages={
                            "unique": "A user with the same personal ID already exists"
                        },
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                ("address", models.CharField(max_length=40)),
                ("city", models.CharField(max_length=40)),
                ("state", models.CharField(max_length=40)),
                ("country", models.CharField(max_length=40)),
                ("phone_number", models.CharField(blank=True, max_length=17)),
            ],
            options={
                "ordering": ["-personal_id"],
            },
        ),
    ]
